"""
Dynamic Tool: fisheye_effect
Auto-generated by Agent
"""

import json
import logging
from typing import Dict, Any
import sys
from pathlib import Path

# Add project root to Python path
project_root = Path(__file__).parent.parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from python.tools.base import BaseTool, ToolResult


class DynamicFisheye_effectTool(BaseTool):
    """Dynamic tool: fisheye_effect"""
    
    def __init__(self):
        super().__init__()
        self.name = "fisheye_effect"
        self.description = "Dynamic tool created by agent"
        # Store the actual code
        self.code = """import cv2
import numpy as np
from PIL import Image
import os
from pathlib import Path

def apply_fisheye(input_path, output_path, strength=0.5):

    # 检查输入文件是否存在
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"输入文件不存在: {input_path}")
    
    # 读取图片
    img = cv2.imread(input_path)
    if img is None:
        raise ValueError("无法读取图片文件")
    
    # 获取图片尺寸
    rows, cols = img.shape[:2]
    
    # 创建鱼眼效果映射
    map_x = np.zeros((rows, cols), np.float32)
    map_y = np.zeros((rows, cols), np.float32)
    
    center_x, center_y = cols/2, rows/2
    radius = min(center_x, center_y)
    
    for y in range(rows):
        for x in range(cols):
            # 计算到中心的距离
            dx = x - center_x
            dy = y - center_y
            distance = np.sqrt(dx*dx + dy*dy)
            
            if distance < radius:
                # 应用鱼眼变形
                r = distance / radius
                theta = 1 - r*r*strength
                
                new_x = center_x + dx * theta
                new_y = center_y + dy * theta
                
                map_x[y,x] = new_x
                map_y[y,x] = new_y
            else:
                map_x[y,x] = x
                map_y[y,x] = y
    
    # 应用变形
    fisheye_img = cv2.remap(img, map_x, map_y, cv2.INTER_LINEAR)
    
    # 确保输出目录存在
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # 保存结果
    success = cv2.imwrite(output_path, fisheye_img)
    if not success:
        raise ValueError("保存图片失败")
    
    return f"鱼眼效果处理完成，保存至: {output_path}"

# 处理上传的图片
input_image = "20250804_140404_QQ20250309-120836.png"
output_image = "web/uploads/fisheye_" + input_image
result = apply_fisheye(input_image, output_image, strength=0.5)
print(result)"""
    
    async def execute(self, **kwargs) -> ToolResult:
        """Execute the dynamic tool"""
        try:
            # Parameter validation
            validated_params = self._validate_parameters(kwargs)
            
            # Execute dynamic code
            result = self._execute_dynamic_code(validated_params)
            
            return ToolResult(
                success=True,
                data={"result": result},
                error=None,
                metadata={"tool_type": "dynamic", "tool_name": self.name}
            )
            
        except Exception as e:
            return ToolResult(
                success=False,
                data={},
                error=str(e)
            )
    
    def _validate_parameters(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """Validate parameters"""
        try:
            validated_params = {}
            
            for key, value in params.items():
                # Basic type checking
                if not isinstance(key, str):
                    logging.warning(f"Invalid parameter key type: {type(key)}")
                    continue
                
                # Value validation
                if value is None:
                    logging.warning(f"Parameter '{key}' is None")
                    continue
                
                # String length limit
                if isinstance(value, str) and len(value) > 10000:
                    logging.warning(f"Parameter '{key}' string too long: {len(value)} characters")
                    value = value[:10000] + "..."
                
                # List length limit
                if isinstance(value, list) and len(value) > 1000:
                    logging.warning(f"Parameter '{key}' list too long: {len(value)} items")
                    value = value[:1000]
                
                # Dictionary depth limit
                if isinstance(value, dict):
                    value = self._validate_dict_depth(value, max_depth=5)
                
                validated_params[key] = value
            
            return validated_params
            
        except Exception as e:
            logging.error(f"Parameter validation failed: {e}")
            return params
    
    def _validate_dict_depth(self, data: Dict[str, Any], max_depth: int = 5, current_depth: int = 0) -> Dict[str, Any]:
        """Validate dictionary depth to prevent deep nesting"""
        if current_depth >= max_depth:
            logging.warning(f"Dictionary depth limit reached: {current_depth}")
            return {"error": "Dictionary too deep"}
        
        validated = {}
        for key, value in data.items():
            if isinstance(value, dict):
                validated[key] = self._validate_dict_depth(value, max_depth, current_depth + 1)
            else:
                validated[key] = value
        
        return validated
    
    def _execute_dynamic_code(self, params: Dict[str, Any]) -> Any:
        """Execute dynamic code"""
        try:
            # Create local variable environment
            local_vars = {}
            local_vars.update(params)
            
            # Execute code (define functions)
            exec(self.code, {}, local_vars)
            
            # Intelligently detect callable functions
            callable_functions = []
            for name, obj in local_vars.items():
                if callable(obj) and not name.startswith('_'):
                    callable_functions.append(name)
            
            if callable_functions:
                # Select the most appropriate function
                # Prefer function with same name as tool
                tool_name = self.name
                if tool_name in callable_functions:
                    selected_function = tool_name
                else:
                    # Otherwise select the first callable function
                    selected_function = callable_functions[0]
                
                # Call the selected function
                func = local_vars[selected_function]
                if params:
                    # Try to call function with parameters
                    try:
                        # If function accepts parameters, pass the first parameter
                        first_param = next(iter(params.values()))
                        return func(first_param)
                    except (TypeError, ValueError):
                        # If parameter type doesn't match, try calling without parameters
                        return func()
                else:
                    # Call without parameters
                    return func()
            
            # If no callable function found, check for result variable
            if 'result' in local_vars:
                return local_vars['result']
            
            # If none found, return local variables after execution
            return local_vars
            
        except Exception as e:
            logging.error(f"Dynamic code execution failed: {e}")
            return None
